# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://chinakarl.github.io/
date_format: "ordinal"
title: karl
subtitle: "coding人生"
description: "小石头的个人博客"
keywords: 小石头, stone
favicon: /favicon.ico
timezone: China/JiangSu
encoding: "utf-8"
side_bar_repo_limit: 5


# ---------------- #
#      Author      #
# ---------------- #
author: Stone
organization: 
organization_url: 
github_username: chinakarl
location: JiangSu, China
email: netzhaihaixiang@sina.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chinakarl/chinakarl.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: mzlogin
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: chinakarl
    repo: karl
    oauth:
        client_id: daa4407e403e07722879
        client_secret: 737938ef2dfe9d5ab793f5ee9ad802c87238b4ca
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: chinakarl
    repo: karl
    clientID: daa4407e403e07722879
    clientSecret: 737938ef2dfe9d5ab793f5ee9ad802c87238b4ca
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
